config:
  processor: "../functions.js"
  payload:
    -
      path: "../payload/{{ $environment }}/campaigns.csv"
      fields:
        - "campaignCode"
      order: random
      skipHeader: true
    -
      path: "../payload/{{ $environment }}/users-orga.csv"
      fields:
        - "username"
        - "password"
      order: random
      skipHeader: true
  environments:
    localhost:
      target: http://localhost:3000
      phases:
      - duration: 60
        arrivalRate: 5
        name: "Slowly warming up the application"
      - duration: 120
        arrivalRate: 5
        rampTo: 50
        name: "Warm up the application"
      - duration: 600
        arrivalRate: 50
        name: "Sustained max load"
    benchmark:
      target:  https://pix-api-benchmark.scalingo.io
      phases:
        - duration: 3600
          arrivalCount: 5400
          name: "Benchmarking Mon-Pix"
#        - duration: 1800
#          arrivalCount: 300
#          name: "Benchmarking Orga"

  variables:
    # Thinking time is in seconds
    needRandomThinkingTime: true
    minThinkingTime: 30
    maxThinkingTime: 90
